# Generated by Django 3.2.7 on 2021-11-20 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='prj_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
