# Generated by Django 3.2.7 on 2021-12-08 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0003_alter_project_prj_datecreated'),
    ]

    operations = [
        migrations.CreateModel(
            name='G_LocationDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gen_SettlementName', models.CharField(max_length=50, null=True)),
                ('gen_StateName', models.CharField(max_length=50, null=True)),
                ('gen_CountryName', models.CharField(max_length=50, null=True)),
                ('gen_Currency', models.CharField(max_length=5, null=True)),
                ('gen_Notes', models.TextField(blank=True, null=True)),
                ('gen_Source', models.TextField(blank=True, null=True)),
                ('gen_idProject', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='base.project')),
                ('gen_idUser', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='G_Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gen_ResidentialIncome', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('gen_ResidentialWillingness', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('gen_CommercialIncome', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('gen_CommercialWillingness', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('gen_Notes', models.TextField(blank=True, null=True)),
                ('gen_Source', models.TextField(blank=True, null=True)),
                ('gen_idProject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.project')),
                ('gen_idUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='G_Fuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gen_CommercialFuelUsed', models.CharField(blank=True, max_length=20, null=True)),
                ('gen_CommercialFuelMonthly', models.FloatField(blank=True, null=True)),
                ('gen_CommercialFuelCost', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('gen_ResidentialFuelUsed', models.CharField(blank=True, max_length=20, null=True)),
                ('gen_ResidentialFuelMonthly', models.FloatField(blank=True, null=True)),
                ('gen_ResidentialFuelCost', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('gen_Notes', models.TextField(blank=True, null=True)),
                ('gen_Source', models.TextField(blank=True, null=True)),
                ('gen_idProject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.project')),
                ('gen_idUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='G_Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gen_WorldBankTier', models.CharField(blank=True, max_length=50, null=True)),
                ('gen_Notes', models.TextField(blank=True, null=True)),
                ('gen_Source', models.TextField(blank=True, null=True)),
                ('gen_idProject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.project')),
                ('gen_idUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='G_Demography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gen_PopulationSettlement', models.IntegerField(blank=True, null=True)),
                ('gen_PopulationConnected', models.IntegerField(blank=True, null=True)),
                ('gen_ResidentialProperties', models.IntegerField(blank=True, null=True)),
                ('gen_ResidentialConnected', models.IntegerField(blank=True, null=True)),
                ('gen_CommercialProperties', models.IntegerField(blank=True, null=True)),
                ('gen_CommercialConnected', models.IntegerField(blank=True, null=True)),
                ('gen_Notes', models.TextField(blank=True, null=True)),
                ('gen_Source', models.TextField(blank=True, null=True)),
                ('gen_idProject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.project')),
                ('gen_idUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
