# Generated by Django 3.2.7 on 2021-12-12 02:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0004_g_demography_g_discount_g_fuel_g_income_g_locationdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='g_discount',
            name='gen_WorldBankTier',
        ),
        migrations.AddField(
            model_name='g_discount',
            name='gen_DiscountRate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='G_Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gen_StartingYear', models.IntegerField(blank=True, null=True)),
                ('gen_ProjectionPeriod', models.IntegerField(blank=True, null=True)),
                ('gen_MonthsNumber', models.IntegerField(blank=True, null=True)),
                ('gen_Notes', models.TextField(blank=True, null=True)),
                ('gen_Source', models.TextField(blank=True, null=True)),
                ('gen_idProject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.project')),
                ('gen_idUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='G_Tier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gen_WorldBankTier', models.CharField(blank=True, max_length=50, null=True)),
                ('gen_Notes', models.TextField(blank=True, null=True)),
                ('gen_Source', models.TextField(blank=True, null=True)),
                ('gen_idProject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.project')),
                ('gen_idUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
