# Generated by Django 3.2.7 on 2021-12-12 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20211211_2138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='g_fuel',
            name='gen_idProject',
        ),
        migrations.RemoveField(
            model_name='g_fuel',
            name='gen_idUser',
        ),
        migrations.RemoveField(
            model_name='g_income',
            name='gen_idProject',
        ),
        migrations.RemoveField(
            model_name='g_income',
            name='gen_idUser',
        ),
        migrations.RemoveField(
            model_name='g_tier',
            name='gen_idProject',
        ),
        migrations.RemoveField(
            model_name='g_tier',
            name='gen_idUser',
        ),
        migrations.RemoveField(
            model_name='g_time',
            name='gen_idProject',
        ),
        migrations.RemoveField(
            model_name='g_time',
            name='gen_idUser',
        ),
        migrations.DeleteModel(
            name='G_Discount',
        ),
        migrations.DeleteModel(
            name='G_Fuel',
        ),
        migrations.DeleteModel(
            name='G_Income',
        ),
        migrations.DeleteModel(
            name='G_Tier',
        ),
        migrations.DeleteModel(
            name='G_Time',
        ),
    ]
