# Generated by Django 3.2.7 on 2022-01-13 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_g_discount_g_fuel_g_income_g_tier_g_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='g_demography',
            name='gen_CommercialConnectedUnit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='g_demography',
            name='gen_CommercialPropertiesUnit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='g_demography',
            name='gen_PopulationConnectedUnit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='g_demography',
            name='gen_PopulationSettlementUnit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='g_demography',
            name='gen_ResidentialConnectedUnit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='g_demography',
            name='gen_ResidentialPropertiesUnit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='g_discount',
            name='gen_DiscountRateUnit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='g_fuel',
            name='gen_CommercialFuelCostUnit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='g_fuel',
            name='gen_CommercialFuelMonthlyUnit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='g_fuel',
            name='gen_ResidentialFuelCostUnit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='g_fuel',
            name='gen_ResidentialFuelMonthlyUnit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='g_income',
            name='gen_CommercialIncomeUnit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='g_income',
            name='gen_CommercialWillingnessUnit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='g_income',
            name='gen_ResidentialIncomeUnit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='g_income',
            name='gen_ResidentialWillingnessUnit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='g_tier',
            name='gen_WorldBankTierUnit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='g_time',
            name='gen_MonthsNumberUnit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='g_time',
            name='gen_ProjectionPeriodUnit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='g_discount',
            name='gen_DiscountRate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='g_fuel',
            name='gen_CommercialFuelCost',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='g_fuel',
            name='gen_CommercialFuelMonthly',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='g_fuel',
            name='gen_ResidentialFuelCost',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='g_fuel',
            name='gen_ResidentialFuelMonthly',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='g_income',
            name='gen_CommercialIncome',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='g_income',
            name='gen_CommercialWillingness',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='g_income',
            name='gen_ResidentialIncome',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='g_income',
            name='gen_ResidentialWillingness',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
    ]
