# Generated by Django 3.2.7 on 2022-01-14 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_r_average_r_changes_r_growth_r_options_r_rates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='r_options',
            name='rev_FixedCostKwhOp3',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='r_options',
            name='rev_FixedCostOp1',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='r_options',
            name='rev_KwhConsumpOp2',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
