# Generated by Django 3.2.7 on 2022-02-09 03:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_co2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='r_rates',
            name='rev_FixedCostCommercialOp1',
            field=models.FloatField(blank=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='r_rates',
            name='rev_FixedCostCommercialOp3',
            field=models.FloatField(blank=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='r_rates',
            name='rev_FixedCostResidentialOp1',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='r_rates',
            name='rev_FixedCostResidentialOp3',
            field=models.FloatField(blank=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='r_rates',
            name='rev_KwhCommercialOp3',
            field=models.FloatField(blank=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='r_rates',
            name='rev_KwhResidentialOp2',
            field=models.FloatField(blank=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='r_rates',
            name='rev_KwhResidentialOp3',
            field=models.FloatField(blank=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='r_rates',
            name='rev_kwhCommercialOp2',
            field=models.FloatField(blank=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
