# Generated by Django 3.2.7 on 2022-02-09 06:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_auto_20220208_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='co2',
            name='co2_CurrentFactor',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, validators=[django.core.validators.DecimalValidator]),
        ),
        migrations.AlterField(
            model_name='co2',
            name='co2_Diesel',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, validators=[django.core.validators.DecimalValidator]),
        ),
        migrations.AlterField(
            model_name='co2',
            name='co2_EmissionCar',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, validators=[django.core.validators.DecimalValidator]),
        ),
        migrations.AlterField(
            model_name='co2',
            name='co2_Kerosene',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, validators=[django.core.validators.DecimalValidator]),
        ),
        migrations.AlterField(
            model_name='co2',
            name='co2_ProductionPerLitre',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, validators=[django.core.validators.DecimalValidator]),
        ),
        migrations.AlterField(
            model_name='co2',
            name='co2_WoodLogs',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, validators=[django.core.validators.DecimalValidator]),
        ),
        migrations.AlterField(
            model_name='g_discount',
            name='gen_DiscountRate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.DecimalValidator]),
        ),
        migrations.AlterField(
            model_name='g_fuel',
            name='gen_CommercialFuelCost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.DecimalValidator]),
        ),
        migrations.AlterField(
            model_name='g_fuel',
            name='gen_CommercialFuelMonthly',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.DecimalValidator]),
        ),
        migrations.AlterField(
            model_name='g_fuel',
            name='gen_ResidentialFuelCost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.DecimalValidator]),
        ),
        migrations.AlterField(
            model_name='g_fuel',
            name='gen_ResidentialFuelMonthly',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.DecimalValidator]),
        ),
        migrations.AlterField(
            model_name='g_income',
            name='gen_CommercialIncome',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.DecimalValidator]),
        ),
        migrations.AlterField(
            model_name='g_income',
            name='gen_CommercialWillingness',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.DecimalValidator]),
        ),
        migrations.AlterField(
            model_name='g_income',
            name='gen_ResidentialIncome',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.DecimalValidator]),
        ),
        migrations.AlterField(
            model_name='g_income',
            name='gen_ResidentialWillingness',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.DecimalValidator]),
        ),
        migrations.AlterField(
            model_name='p_capital',
            name='pla_InstallationCost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.DecimalValidator]),
        ),
        migrations.AlterField(
            model_name='p_details',
            name='pla_AnnualDegradation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.DecimalValidator]),
        ),
        migrations.AlterField(
            model_name='p_details',
            name='pla_BatterySize',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.DecimalValidator]),
        ),
        migrations.AlterField(
            model_name='p_details',
            name='pla_DailyGeneration',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.DecimalValidator]),
        ),
        migrations.AlterField(
            model_name='p_details',
            name='pla_PlantSize',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.DecimalValidator]),
        ),
        migrations.AlterField(
            model_name='p_operational',
            name='pla_OMEscalator',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.DecimalValidator]),
        ),
        migrations.AlterField(
            model_name='p_replacement',
            name='pla_FirstBatteriesSize',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.DecimalValidator]),
        ),
        migrations.AlterField(
            model_name='p_replacement',
            name='pla_FirstPlantAdded',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.DecimalValidator]),
        ),
        migrations.AlterField(
            model_name='p_replacement',
            name='pla_SecondBatteriesSize',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.DecimalValidator]),
        ),
        migrations.AlterField(
            model_name='p_replacement',
            name='pla_SecondPlantAdded',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.DecimalValidator]),
        ),
        migrations.AlterField(
            model_name='p_replacement',
            name='pla_ThirdBatteriesSize',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.DecimalValidator]),
        ),
        migrations.AlterField(
            model_name='p_replacement',
            name='pla_ThirdPlantAdded',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.DecimalValidator]),
        ),
        migrations.AlterField(
            model_name='p_subsidy',
            name='pla_SubsidyCapital',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.DecimalValidator]),
        ),
        migrations.AlterField(
            model_name='p_subsidy',
            name='pla_SubsidyOperational',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.DecimalValidator]),
        ),
        migrations.AlterField(
            model_name='p_subsidy',
            name='pla_SubsidyReplacement',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.DecimalValidator]),
        ),
        migrations.AlterField(
            model_name='r_average',
            name='rev_CommercialConsump',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.DecimalValidator]),
        ),
        migrations.AlterField(
            model_name='r_average',
            name='rev_ResidentialConsump',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.DecimalValidator]),
        ),
        migrations.AlterField(
            model_name='r_changes',
            name='rev_FifthYearPercentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.DecimalValidator]),
        ),
        migrations.AlterField(
            model_name='r_changes',
            name='rev_FirstYearPercentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.DecimalValidator]),
        ),
        migrations.AlterField(
            model_name='r_changes',
            name='rev_FourthYearPercentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.DecimalValidator]),
        ),
        migrations.AlterField(
            model_name='r_changes',
            name='rev_SecondYearPercentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.DecimalValidator]),
        ),
        migrations.AlterField(
            model_name='r_changes',
            name='rev_ThirdYearPercentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.DecimalValidator]),
        ),
        migrations.AlterField(
            model_name='r_growth',
            name='rev_CommercialGrowth',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.DecimalValidator]),
        ),
        migrations.AlterField(
            model_name='r_growth',
            name='rev_ResidentialGrowth',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.DecimalValidator]),
        ),
        migrations.AlterField(
            model_name='r_options',
            name='rev_UnchargedCommercialOp3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.DecimalValidator]),
        ),
        migrations.AlterField(
            model_name='r_options',
            name='rev_UnchargedResidentialOp3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.DecimalValidator]),
        ),
    ]
